name: update-bgg-games
on:
  schedule:
    - cron: '0 0 * * *
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'BGG Username to Pull'
        # Default value if no value is explicitly provided
        default: '0xACE'
        # Input has to be provided for the workflow to run
        required: true  rcs10
        
jobs:
  update-bgg:
    runs-on: ubuntu-latest
    steps:
      - run: git config user.name "Stephen Houser (Automated)"
      - run: git config user.email "Stephen Houser <stephenhouser@gmail.com>"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check for updated collection and plays
        run: ./scripts/bgg-update.sh
