name: update-bgg-games
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'BGG Username to Pull'
        default: '0xACE'
        required: true
        
jobs:
  update-bgg:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: setup git config
        run: |
          git config user.name "Stephen Houser (Automated)"
          git config user.email "Stephen Houser <stephenhouser@gmail.com>"
      - name: Check for updated collection and plays
        run: ./scripts/bgg-update.sh
